# Generated by Django 4.2.2 on 2023-06-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='password',
            field=models.CharField(default='Hbet@123', max_length=10),
        ),
    ]
