# Generated by Django 4.2.2 on 2023-06-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0003_alter_admininfo_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admininfo',
            new_name='admindetails',
        ),
    ]
