# Generated by Django 4.2.2 on 2023-06-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0005_admin_details_delete_admindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_details',
            name='email',
            field=models.EmailField(default='NA', max_length=254),
        ),
        migrations.AddField(
            model_name='admin_details',
            name='full_name',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
