# Generated by Django 4.2.2 on 2023-07-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0010_alter_donor_details_spouse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_details',
            name='full_name',
            field=models.CharField(default='NA', max_length=128),
        ),
    ]
