# Generated by Django 4.2.2 on 2023-07-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0011_alter_donor_details_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_details',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donor_details',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
