# Generated by Django 4.2.2 on 2023-07-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0014_donor_details_delete_donor_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_details',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
