# Generated by Django 4.2.2 on 2023-07-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0015_alter_donor_details_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_details',
            name='mobile_number1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donor_details',
            name='mobile_number2',
            field=models.TextField(null=True),
        ),
    ]
