# Generated by Django 4.2.2 on 2023-07-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0016_alter_donor_details_mobile_number1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='donor_details',
        ),
    ]
