# Generated by Django 4.2.2 on 2023-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0018_donor_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_details',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
