# Generated by Django 4.2.2 on 2023-07-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0020_alter_admin_details_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_details',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admin_details',
            name='full_name',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='admin_details',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donor_details',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='donor_details',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='donor_details',
            name='full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='donor_details',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donor_details',
            name='mobile_number1',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='donor_details',
            name='mobile_number2',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='donor_details',
            name='spouse_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donor_details',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
