# Generated by Django 4.2.2 on 2023-07-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0021_alter_admin_details_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_details',
            name='aadhar_card_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
