# Generated by Django 4.2.2 on 2023-07-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0022_alter_donor_details_aadhar_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor_details',
            name='aadhar_card_number',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='date_of_marriage',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='date_of_registration',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='mobile_number1',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='mobile_number2',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='pan_card_number',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='state',
        ),
    ]
