# Generated by Django 4.2.2 on 2023-07-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0023_remove_donor_details_aadhar_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor_details',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='donor_details',
            name='password',
        ),
    ]
