# Generated by Django 4.2.2 on 2023-07-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0025_donor_delete_donor_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donor',
            table=None,
        ),
    ]
