# Generated by Django 4.2.2 on 2023-07-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0026_alter_donor_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='spouse_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
