# Generated by Django 4.2.2 on 2023-07-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0029_alter_donor_aadhar_card_number_alter_donor_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('dom', models.DateField(blank=True, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('dor', models.DateField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=6)),
                ('mobile2', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile1', models.CharField(max_length=20)),
                ('aadhar_card', models.BigIntegerField(blank=True, null=True)),
                ('pan_card', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'donor_details',
            },
        ),
        migrations.DeleteModel(
            name='donor',
        ),
    ]
