# Generated by Django 4.2.2 on 2023-07-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0031_alter_donordetails_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='dom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
