# Generated by Django 4.2.2 on 2023-07-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0032_alter_donordetails_dom'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donordetails',
            table='donor_personal_details',
        ),
    ]
