# Generated by Django 4.2.2 on 2023-07-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBETCODE', '0033_alter_donordetails_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donordetails',
            table=None,
        ),
    ]
